version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data

  shelter-client:
    container_name: shelter-client
    build:
      context: ./apps/shelter-client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  shelter-gateway:
    container_name: shelter-gateway
    build:
      context: .
      dockerfile: ./apps/shelter-gateway/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgresql
    ports:
      - '8000:8000'

  shelter-accounts:
    container_name: shelter-accounts
    build:
      context: .
      dockerfile: ./apps/shelter-accounts/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgresql
    ports:
      - '8001:8001'

  shelter-ml:
    container_name: shelter-ml
    build:
      context: ./apps/shelter-ml
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '8008:8008'
