services:
 - type: postgres
    name: shelter-postgres
    plan: free
    env: postgres
    properties:
      version: "16"
      database: 
        name: root
        user: root
        password: root

  - type: web
    name: shelter-client
    env: docker
    dockerfilePath: ./apps/shelter-client/Dockerfile
    plan: free

  - type: web
    name: shelter-gateway
    env: docker
    dockerfilePath: ./apps/shelter-gateway/Dockerfile
    plan: free

  - type: web
    name: shelter-accounts
    env: docker
    dockerfilePath: ./apps/shelter-accounts/Dockerfile
    plan: free

  - type: web
    name: shelter-ml
    env: docker
    dockerfilePath: ./apps/shelter-ml/Dockerfile
    plan: free