services:
  - name: postgresql
    env:
      - key: POSTGRES_DB
        value: root
      - key: POSTGRES_USER
        value: root
      - key: POSTGRES_PASSWORD
        value: root
    instanceType: Standard
    disk: 10
    plan: free
    ports:
      - 5432
    environment:
      - PGDATA: /var/lib/postgresql/data

  - name: shelter-client
    buildCommand: |
      docker build -t shelter-client ./apps/shelter-client
    startCommand: |
      docker run -d -p 8080:80 shelter-client
    plan: free

  - name: shelter-gateway
    buildCommand: |
      docker build -t shelter-gateway -f ./apps/shelter-gateway/Dockerfile .
    startCommand: |
      docker run -d -p 8000:8000
    plan: free

  - name: shelter-accounts
    buildCommand: |
      docker build -t shelter-accounts -f ./apps/shelter-accounts/Dockerfile .
    startCommand: |
      docker run -d -p 8001:8001
    plan: free

  - name: shelter-ml
    buildCommand: |
      docker build -t shelter-ml ./apps/shelter-ml
    startCommand: |
      docker run -d -p 8008:8008
    plan: free